name: "MSSQL Sample DB"
author: "lowlydba"
branding:
  icon: "database"
  color: "red"
description: "Restores sample databases to an instance."
inputs:
  sql-instance:
    description: "Target SQL instance."
    required: false
    default: "localhost"
  database:
    description: "Sample database to download and restore."
    required: false
    default: "WideWorldImporters"
runs:
  using: "composite"
  steps:
    - shell: pwsh
      run: |
        $params = @{
          Database = "${{ inputs.database }}"
          SqlInstance = "${{ inputs.sql-instance }}"
        }

        ${{github.action_path}}\main.ps1 @params
