name: "TSQLLint Action"
author: "lowlydba"
description: "Lint T-SQL files using TSQLLint"
branding:
  icon: "check-circle"
  color: "green"
inputs:
  path:
    description: "Space separated path(s) to run linter against. Wildcards can be specified using `*`."
    required: false
    default: "*.sql"
  config:
    description: "Path to a configuration file for the linter."
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.path }}
    - ${{ inputs.config }}
