name: "TSQLLint Action"
author: "lowlydba"
description: "Lint T-SQL files using TSQLLint"
branding:
  icon: "check-circle"
  color: "green"
inputs:
  path:
    description: "Space separated path(s) to run linter against. Wildcards can be specified using `*`."
    required: false
    default: "*.sql"
  config:
    description: "Path to a configuration file for the linter."
    required: false
runs:
  using: composite
  steps:
    - name: Install TSQLLint
      run: |
        DEBIAN_FRONTEND=noninteractive && \
        apt-get -qq update && \
        apt-get -qq install libunwind8  && \
        yarn global add tsqllint
      shell: bash

    - name: Run TSQLLint
      run: |
        if [ -z ${{ inputs.config }} ]
          then
            echo "No config file found, using defaults."
            tsqllint ${{ inputs.path }}
          else
            echo "Using config file at ${{inputs.config }}"
            tsqllint ${{ inputs.path }} -c ${{inputs.config }}
        fi
      shell: bash
