name: "TSQLLint Action"
author: "lowlydba"
description: "Lint T-SQL files using TSQLLint"
branding:
  icon: "check-circle"
  color: "green"
inputs:
  path:
    description: "Space separated path(s) to run linter against. Wildcards can be specified using `*`."
    required: false
    default: "*.sql"
  config:
    description: "Path to a configuration file for the linter."
    required: false
runs:
  using: composite
  steps:
    - name: Install TSQLLint
      run: |
        DEBIAN_FRONTEND=noninteractive && \
        sudo apt-get -qq update && \
        sudo apt-get -qq install libunwind8  && \
        yarn global add tsqllint > /dev/null 2>&1
      shell: bash

    - name: Run TSQLLint
      run: |
        if [ -z ${{ inputs.config }} ]
          then
            echo "No config file found, using defaults."
            tsqllint ${{ inputs.path }} > .tsqllint-output
          else
            echo "Using config file at ${{ inputs.config }}"
            tsqllint ${{ inputs.path }} -c ${{ inputs.config }} > .tsqllint-output
        fi
      shell: bash

    - name: Show results
      run: |
        cat .tsqllint-output
      shell: bash

    - name: Get Status
      run: |
        warnings=`cat .tsqllint-output | tail -1`
        errors=`cat .tsqllint-output | tail -2 | head -1`
      shell: bash

    - name: Generate comment
      #if: contains(inputs.publish, 'true')
      run: |
        if [[ ${warnings:0:1} == "0" -a ${errors:0:1} == "0" ]]; then status=":white_check_mark:"; else status=":x:"; fi
        echo -e "## $status TSQLLint Summary\n" >> .tsqllint-output.final
        cat .tsqllint-output | tail -4 >> .tsqllint-output.final
        echo -e "\nResults for commit ${{ github.sha }}." >> .tsqllint-output.final
        echo -e "\n[Detailed results.]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)" >> .tsqllint-output.final
        echo -e "\n:recycle: This comment has been updated with latest results." >> .coverage-output.final
      shell: bash

      #https://github.com/lowlydba/dba-multitool/runs/8052423233?check_suite_focus=true

    - name: Post as comment
      #if: contains(inputs.publish, 'true')
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: .tsqllint-output.final
