name: "tSQLt Installer"
author: "lowlydba"
branding:
  icon: "database"
  color: "blue"
description: "Installs tSQLt."
inputs:
  sql-instance:
    description: "Target SQL instance."
    required: false
    default: "localhost"
  database:
    description: "Target database to install to."
    required: false
    default: "master"
  user:
    description: "Optional user for SQL authentication."
    required: false
  password:
    description: "Optional password for SQL authentication."
    required: false
  version:
    description: "Version to install."
    required: false
    default: "latest"
runs:
  using: "composite"
  steps:
    - shell: pwsh
      run: |
        $params = @{
          SqlInstance = "${{ inputs.sql-instance }}"
          Database = "${{ inputs.database }}"
          Version = "${{ inputs.version }}"
          User = "${ inputs.user }}"
          Password = "${ inputs.password }}"
        }

        ${{github.action_path}}/main.ps1 @params
