name: "SQLCover"
author: "lowlydba"
branding:
  icon: "database"
  color: "purple"
description: "Installs, starts, and stops SQLCover by GoEddie."
inputs:
  sql-instance:
    description: "Target SQL instance. Only used by the 'start' action."
    required: false
    default: "localhost"
  database:
    description: "Target database. Only used by the 'start' action."
    required: false
    default: "master"
  action:
    description: "Whether to 'install,', 'start', or 'stop' SQLCover. Start includes install by default."
    required: true
  output-path:
    description: "Path to output results to. Only used by the 'start' action."
    required: false
    default: sqlcover
runs:
  using: "composite"
  steps:
    - id: output
      shell: pwsh
      env:
        STOP_FILE: "stop.txt"
        COV_FILE: "coverage.xml"
        SLEEP_SEC: "5"
        OUTPUT_PATH: "${{ inputs.output-path }}"
        SQLINSTANCE: "${{ inputs.sql-instance }}"
        DATABASE: "${{ inputs.database }}"
      run: |
        $params = @{
          Action = "${{ inputs.action }}"
        }

        ${{github.action_path}}\main.ps1 @params
