name: "SQLCover"
author: "lowlydba"
branding:
  icon: "database"
  color: "purple"
description: "Installs, starts, and stops SQLCover by GoEddie."
inputs:
  sql-instance:
    description: "Target SQL instance. Only used by the 'start' action."
    required: false
    default: "localhost"
  database:
    description: "Target database. Only used by the 'start' action."
    required: false
    default: "master"
  output-path:
    description: "Path to output results to. Only used by the 'start' action."
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - id: output
      shell: pwsh
      env:
        COV_FILE: "cobertura.xml"
        OUTPUT_PATH: "${{ inputs.output-path }}"
        SQLINSTANCE: "${{ inputs.sql-instance }}"
        DATABASE: "${{ inputs.database }}"
        PACKAGE: "GOEddie.SQLCover"
      run: |
        $params = @{
          Action = "start"
        }

        ${{github.action_path}}\main.ps1 @params
