---
name: Generate Artifacts
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .vscode/*
  pull_request:
    paths-ignore:
      - .vscode/*

# Cancel existing runs on new commits to a branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  INSTALLER_FILE: "install_dba-multitool.sql"
  SAMPLE_DATABASE: "WideWorldImporters"
  SP_DOC_FILE: "WideWorldImporters.md"
  SQLINSTANCE: "localhost"
  DATABASE: "master"

jobs:
  bundle:
    runs-on: ubuntu-latest
    name: Generate artifacts
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Check out code
        uses: actions/checkout@v3.0.2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install and cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v4.5
        with:
          modules-to-cache: dbatools
          shell: pwsh

      - name: Create bundled installer script
        run: |
          Get-ChildItem -Path $Env:GITHUB_WORKSPACE -Filter "sp_*.sql" | Get-Content | Out-File $Env:INSTALLER_FILE -Encoding ascii
          Get-ChildItem -Path $Env:GITHUB_WORKSPACE -Filter $Env:INSTALLER_FILE | Select-Object -Property Name, Size, LastWriteTime, User

      - name: Commit bundled installer script
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: Updated bundled installer
          file_pattern: ${{ env.INSTALLER_FILE }}
