---
name: Generate Bundled Installer
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .vscode/*
  pull_request:
    paths-ignore:
      - .vscode/*

# Cancel existing runs on new commits to a branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  INSTALLER_FILE: "install_dba-multitool.sql"

jobs:
  bundle:
    runs-on: windows-latest
    name: Create bundled installer script

    steps:
      - name: Check out code
        uses: actions/checkout@v3.0.2
        with:
          ref: ${{ github.head_ref }}

      - name: Create installer script
        run: |
          Get-ChildItem -Path $Env:GITHUB_WORKSPACE -Filter "sp_*.sql" | Get-Content | Out-File $Env:INSTALLER_FILE -Encoding ascii
          Get-ChildItem -Path $Env:GITHUB_WORKSPACE -Filter $Env:INSTALLER_FILE

      - name: Commit bundled installer
        uses: stefanzweifel/git-auto-commit-action@4.14.2
        with:
          commit_message: Updated bundled installer
          file_pattern: "*.sql"
