---
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Lint Code
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - install_dba-multitool.sql

jobs:
  build:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.3.0
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Super Linter
        uses: github/super-linter@v4.10.1
        env:
          LINTER_RULES_PATH: .github/linter-conf
          VALIDATE_MARKDOWN: true
          VALIDATE_POWERSHELL: true
          FILTER_REGEX_EXCLUDE: /github/workspace/*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: TSQLLint
        uses: lowlydba/tsqllint-action@main
        with:
          path: "*.sql"
          config: "./.github/linter-conf/.tsqllintrc_150"
          comment: true
          only_changed_files: true
