---
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Lint Code
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.0.2

      - name: Super Linter
        uses: docker://github/super-linter:v3.13.5
        env:
          LINTER_RULES_PATH: .github/linter-conf
          VALIDATE_MARKDOWN: true
          VALIDATE_POWERSHELL: true
          FILTER_REGEX_EXCLUDE: /github/workspace/*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: TSQLLint
        uses: lowlydba/tsqllint-action@main
        with:
          path: "*.sql"
          config: "./.github/linter-conf/.tsqllintrc_150"
          comment: true
