---
#TODO:
# Add SQL 2017 to github runner - https://github.com/potatoqualitee/mssqlsuite/issues/16
# Break out tsqlt action as independent GHA

name: Unit Test (Win SQL Server)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .vscode/*
      - "**.md"
  pull_request:
    paths-ignore:
      - .vscode/*
      - "**.md"

  # Run CI once per day (at 06:00 UTC)
  schedule:
    - cron: "0 6 * * *"

# Cancel existing runs on new commits to a branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SQLINSTANCE: "localhost"
  DATABASE: "tsqlt"
  COVERAGE_HTML_FILE: "coverage.html"
  COBERTURA_FILE: "cobertura.xml"

jobs:
  integration:
    runs-on: ${{ matrix.os }}
    name: sqlserver-${{ matrix.sql_server }} x ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        sql_server:
          - 2019

    steps:
      - name: Check out code
        uses: actions/checkout@v3.0.2
        with:
          path: ""
          ref: ${{ github.head_ref }}

      - name: Install SQL Server
        uses: potatoqualitee/mssqlsuite@v1.4
        with:
          install: sqlengine
          sa-password: L0wlydb4

      - name: Install and cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v4.5
        with:
          modules-to-cache: dbatools
          shell: powershell

      - name: Create database
        run: |
          $null = New-DbaDatabase -SqlInstance $Env:SQLINSTANCE -Database $Env:DATABASE

      - name: Install tSQLt
        uses: lowlydba/tsqlt-installer@v1
        with:
          sql-instance: ${{ env.SQLINSTANCE }}
          database: ${{ env.DATABASE }}
          version: "latest"

      - name: Install multitool
        run: |
          foreach ($script in (Get-ChildItem -Path "." -Filter "sp_*.sql").Name) {
            Invoke-DbaQuery -SqlInstance $Env:SQLINSTANCE -Database $Env:DATABASE -File $script
          }

      - name: Run Pester tests with SQLCover
        uses: ./.github\actions\sqlcover
        with:
          sql-instance: ${{ env.SQLINSTANCE }}
          database: ${{ env.DATABASE }}

      - name: Produce the coverage report
        uses: insightsengineering/coverage-action@v2
        with:
          path: ${{ env.COBERTURA_FILE }}
          threshold: 90
          fail: false
          publish: true
          diff: true
          diff-branch: main

      - name: Upload HTML coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-coverage
          path: ${{ env.COVERAGE_HTML_FILE }}
